import { BlockTypes } from "@/constants/enum";
import { useDirectus } from "@/lib/directus/directus";
import { applyTranslations } from "@/lib/translation";
import { Icon } from "@/types/directus-schema";
import { readItems } from "@directus/sdk";
import { Key } from "react";
import DirectusImage from "../../shared/directus-image";

const fetchValuePropsPremiumData = async (blockId: number, locale: string) => {
  /* eslint-disable react-hooks/rules-of-hooks */
  const { directus } = useDirectus();
  const data = await directus.request(
    readItems(BlockTypes.BLOCK_VALUE_PROPS_PREMIUM, {
      filter: { id: { _eq: blockId } },
      fields: [
        "*",
        {
          items: ["*", { translations: ["*"], icon: ["*"] }],
          translations: ["*"],
          image: ["*"],
        },
      ],
    }),
  );
  const translatedData = applyTranslations(data, locale);
  return translatedData[0];
};

// TODO: Use the type `ValuePropsPremium` generated by directus api
export default async function ValuePropsPremium({ data: { id }, locale }: any) {
  const data = await fetchValuePropsPremiumData(id, locale);
  if (!data) return;
  const { image, headline, items } = data;
  const formattedItems = items.map(
    (item: { icon: { image: any }; headline: any; subheadline: any }) => {
      let iconImg = null;
      if (item?.icon && item.icon?.image) {
        iconImg = item.icon;
      }
      return {
        headline: item.headline,
        subheadline: item.subheadline,
        iconImg,
      };
    },
  );
  return (
    <div
      id={data?.anchor ? `${data?.anchor}` : ""}
      className="relative mx-auto max-w-screen-4xl py-xl"
    >
      {image?.file && (
        <div className="absolute inset-0 -z-10 size-full max-w-screen-4xl grid-cols-2 md:grid md:gap-x-[150px] xl:gap-x-[300px]">
          <div className="relative h-[360px] md:h-full md:max-w-[598px]">
            <DirectusImage
              fill
              className="object-cover px-5 md:px-0 md:py-xl"
              asset={image?.file}
            />
          </div>
        </div>
      )}
      <div className="container flex grid-cols-2 flex-col justify-between gap-y-2xl md:grid md:flex-row md:gap-x-3xl">
        <div className="h-[360px] md:h-full">
          <h3
            className="heading-3 relative top-[65px] z-10 max-h-min max-w-[300px] md:sticky md:top-1/2"
            dangerouslySetInnerHTML={{
              __html: headline || "",
            }}
          />
        </div>
        <div className="relative z-10 flex-1 divide-y divide-[#ECDAA2] border-y border-y-[#ECDAA2] bg-background">
          {/** TODO: Use the type generated by directus api */}
          {formattedItems.map(
            (item: {
              headline: Key | null | undefined;
              iconImg: { image: any; name: string };
              subheadline: any;
            }) => (
              <div
                key={item?.headline}
                className="flex flex-col gap-y-2xl py-2xl"
              >
                <h4
                  className="subtitle"
                  dangerouslySetInnerHTML={{ __html: item?.headline || "" }}
                />
                <div className="flex items-start gap-x-xl md:max-w-[423px]">
                  {item?.iconImg && (
                    <div className="relative mt-0.5 max-h-[19px] min-h-[19px] min-w-[21px] max-w-[21px] text-primary">
                      <DirectusImage fill asset={item?.iconImg as Icon} />
                    </div>
                  )}
                  <div
                    dangerouslySetInnerHTML={{
                      __html: item?.subheadline || "",
                    }}
                  />
                </div>
              </div>
            ),
          )}
        </div>
      </div>
    </div>
  );
}
